# coding=utf-8
import unittest
from test_mathfunc import TestMathFunc
from HTMLTestRunner import HTMLTestRunner
if __name__ == '__main__':
    suite = unittest.TestSuite()   #实例化测试集
    tests = [TestMathFunc('test_add'),TestMathFunc('test_minus'),TestMathFunc('test_divide')]
    suite.addTests(tests)
    #suite.addTests(unittest.TestLoader().loadTestsFromName('test_mathfunc.TestMathFunc'))
    #suite.addTests(unittest.TestLoader().loadTestsFromNames(['test_mathfunc.TestMathFunc']))
    #suite.addTests(unittest.TestLoader().loadTestsFromTestCase(TestMathFunc))
    #runner = unittest.TextTestRunner(verbosity=2)
    #runner.run(suite)
    # with open('UnittestTextReport.txt', 'a') as f:
    #     runner = unittest.TextTestRunner(stream=f, verbosity=2)
    #     runner.run(suite)

    with open('HTMLReport.html', 'w') as f:
        runner = HTMLTestRunner(stream=f,
                                title='MathFunc Test Report',
                                description='generated by HTMLTestRunner.',
                                verbosity=2
                                )
        runner.run(suite)
 #可以看到，执行情况跟我们预料的一样：执行了三个case，并且顺序是按照我们添加进suite的顺序执行的。
#上面用了TestSuite的 addTests() 方法，并直接传入了TestCase列表
#执行此文件，可以看到，在同目录下生成了UnittestTextReport.txt，
#所有的执行报告均输出到了此文件中，这下我们便有了txt格式的测试报告了。
